"""Initial migration with JSONEncoded

Revision ID: 165a94c4e61f
Revises:
Create Date: 2026-03-21 00:55:28.757817

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

import app.adaptadores.modelos_sql
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "165a94c4e61f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "experiencias",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cargo", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("empresa", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("localizacao", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("data_inicio", sa.Date(), nullable=False),
        sa.Column("data_fim", sa.Date(), nullable=True),
        sa.Column(
            "descricao", app.adaptadores.modelos_sql.JSONEncoded(), nullable=True
        ),
        sa.Column(
            "tecnologias", app.adaptadores.modelos_sql.JSONEncoded(), nullable=True
        ),
        sa.Column("atual", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "formacoes",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("curso", app.adaptadores.modelos_sql.JSONEncoded(), nullable=True),
        sa.Column("instituicao", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("localizacao", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("data_inicio", sa.Date(), nullable=False),
        sa.Column("data_fim", sa.Date(), nullable=True),
        sa.Column(
            "descricao", app.adaptadores.modelos_sql.JSONEncoded(), nullable=True
        ),
        sa.Column("atual", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "projetos",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("nome", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "descricao_curta", app.adaptadores.modelos_sql.JSONEncoded(), nullable=True
        ),
        sa.Column(
            "descricao_completa",
            app.adaptadores.modelos_sql.JSONEncoded(),
            nullable=True,
        ),
        sa.Column(
            "tecnologias", app.adaptadores.modelos_sql.JSONEncoded(), nullable=True
        ),
        sa.Column(
            "funcionalidades", app.adaptadores.modelos_sql.JSONEncoded(), nullable=True
        ),
        sa.Column(
            "aprendizados", app.adaptadores.modelos_sql.JSONEncoded(), nullable=True
        ),
        sa.Column("repositorio", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("demo", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("destaque", sa.Boolean(), nullable=False),
        sa.Column("imagem", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sobre",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("titulo", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("localizacao", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("telefone", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("github", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("linkedin", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "descricao", app.adaptadores.modelos_sql.JSONEncoded(), nullable=True
        ),
        sa.Column(
            "disponibilidade", app.adaptadores.modelos_sql.JSONEncoded(), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "stack",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("categoria", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("nivel", sa.Integer(), nullable=False),
        sa.Column("icone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stack")
    op.drop_table("sobre")
    op.drop_table("projetos")
    op.drop_table("formacoes")
    op.drop_table("experiencias")
    # ### end Alembic commands ###
