"""Migrate_TEXT_to_JSON

Revision ID: 541e1b960224
Revises: d0e5794b1dd5
Create Date: 2026-04-11 00:22:31.815176

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "541e1b960224"
down_revision: Union[str, Sequence[str], None] = "d0e5794b1dd5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "experiences",
        "descricao",
        existing_type=sa.VARCHAR(),
        type_=sa.JSON(),
        nullable=True,
        postgresql_using="descricao::json",
    )
    op.alter_column(
        "experiences",
        "tecnologias",
        existing_type=sa.VARCHAR(),
        type_=sa.JSON(),
        nullable=True,
        postgresql_using="tecnologias::json",
    )
    op.alter_column(
        "formacoes",
        "curso",
        existing_type=sa.VARCHAR(),
        type_=sa.JSON(),
        nullable=True,
        postgresql_using="curso::json",
    )
    op.alter_column(
        "formacoes",
        "descricao",
        existing_type=sa.VARCHAR(),
        type_=sa.JSON(),
        nullable=True,
        postgresql_using="descricao::json",
    )
    op.alter_column(
        "projects",
        "descricao_curta",
        existing_type=sa.VARCHAR(),
        type_=sa.JSON(),
        nullable=True,
        postgresql_using="descricao_curta::json",
    )
    op.alter_column(
        "projects",
        "descricao_completa",
        existing_type=sa.VARCHAR(),
        type_=sa.JSON(),
        nullable=True,
        postgresql_using="descricao_completa::json",
    )
    op.alter_column(
        "projects",
        "tecnologias",
        existing_type=sa.VARCHAR(),
        type_=sa.JSON(),
        nullable=True,
        postgresql_using="tecnologias::json",
    )
    op.alter_column(
        "projects",
        "funcionalidades",
        existing_type=sa.VARCHAR(),
        type_=sa.JSON(),
        nullable=True,
        postgresql_using="funcionalidades::json",
    )
    op.alter_column(
        "projects",
        "aprendizados",
        existing_type=sa.VARCHAR(),
        type_=sa.JSON(),
        nullable=True,
        postgresql_using="aprendizados::json",
    )
    op.alter_column(
        "about",
        "descricao",
        existing_type=sa.VARCHAR(),
        type_=sa.JSON(),
        nullable=True,
        postgresql_using="descricao::json",
    )
    op.alter_column(
        "about",
        "disponibilidade",
        existing_type=sa.VARCHAR(),
        type_=sa.JSON(),
        nullable=True,
        postgresql_using="disponibilidade::json",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "about",
        "disponibilidade",
        existing_type=sa.JSON(),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "about",
        "descricao",
        existing_type=sa.JSON(),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "projects",
        "aprendizados",
        existing_type=sa.JSON(),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "projects",
        "funcionalidades",
        existing_type=sa.JSON(),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "projects",
        "tecnologias",
        existing_type=sa.JSON(),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "projects",
        "descricao_completa",
        existing_type=sa.JSON(),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "projects",
        "descricao_curta",
        existing_type=sa.JSON(),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "formacoes",
        "descricao",
        existing_type=sa.JSON(),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "formacoes",
        "curso",
        existing_type=sa.JSON(),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "experiences",
        "tecnologias",
        existing_type=sa.JSON(),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "experiences",
        "descricao",
        existing_type=sa.JSON(),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    # ### end Alembic commands ###
