"""Migrate_TEXT_to_JSON

Revision ID: 541e1b960224
Revises: d0e5794b1dd5
Create Date: 2026-04-11 00:22:31.815176

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "541e1b960224"
down_revision: Union[str, Sequence[str], None] = "d0e5794b1dd5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "experiencias",
        "descricao",
        existing_type=sa.VARCHAR(),
        type_=sa.JSON(),
        nullable=True,
    )
    op.alter_column(
        "experiencias",
        "tecnologias",
        existing_type=sa.VARCHAR(),
        type_=sa.JSON(),
        nullable=True,
    )
    op.alter_column(
        "formacoes", "curso", existing_type=sa.VARCHAR(), type_=sa.JSON(), nullable=True
    )
    op.alter_column(
        "formacoes",
        "descricao",
        existing_type=sa.VARCHAR(),
        type_=sa.JSON(),
        nullable=True,
    )
    op.alter_column(
        "projetos",
        "descricao_curta",
        existing_type=sa.VARCHAR(),
        type_=sa.JSON(),
        nullable=True,
    )
    op.alter_column(
        "projetos",
        "descricao_completa",
        existing_type=sa.VARCHAR(),
        type_=sa.JSON(),
        nullable=True,
    )
    op.alter_column(
        "projetos",
        "tecnologias",
        existing_type=sa.VARCHAR(),
        type_=sa.JSON(),
        nullable=True,
    )
    op.alter_column(
        "projetos",
        "funcionalidades",
        existing_type=sa.VARCHAR(),
        type_=sa.JSON(),
        nullable=True,
    )
    op.alter_column(
        "projetos",
        "aprendizados",
        existing_type=sa.VARCHAR(),
        type_=sa.JSON(),
        nullable=True,
    )
    op.alter_column(
        "sobre", "descricao", existing_type=sa.VARCHAR(), type_=sa.JSON(), nullable=True
    )
    op.alter_column(
        "sobre",
        "disponibilidade",
        existing_type=sa.VARCHAR(),
        type_=sa.JSON(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sobre",
        "disponibilidade",
        existing_type=sa.JSON(),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "sobre",
        "descricao",
        existing_type=sa.JSON(),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "projetos",
        "aprendizados",
        existing_type=sa.JSON(),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "projetos",
        "funcionalidades",
        existing_type=sa.JSON(),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "projetos",
        "tecnologias",
        existing_type=sa.JSON(),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "projetos",
        "descricao_completa",
        existing_type=sa.JSON(),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "projetos",
        "descricao_curta",
        existing_type=sa.JSON(),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "formacoes",
        "descricao",
        existing_type=sa.JSON(),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "formacoes",
        "curso",
        existing_type=sa.JSON(),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "experiencias",
        "tecnologias",
        existing_type=sa.JSON(),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "experiencias",
        "descricao",
        existing_type=sa.JSON(),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    # ### end Alembic commands ###
