"""remove spam filter table

Revision ID: d0e5794b1dd5
Revises: fa6a68f4fdfd
Create Date: 2026-04-09 14:19:31.591894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0e5794b1dd5'
down_revision: Union[str, Sequence[str], None] = 'fa6a68f4fdfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_spam_filter_timestamp', table_name='spam_filter')
    op.drop_table('spam_filter')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spam_filter',
    sa.Column('content_hash', sa.VARCHAR(), nullable=False),
    sa.Column('timestamp', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('content_hash')
    )
    op.create_index('ix_spam_filter_timestamp', 'spam_filter', ['timestamp'], unique=False)
    # ### end Alembic commands ###
