"""Add spam filter table

Revision ID: fa6a68f4fdfd
Revises: 165a94c4e61f
Create Date: 2026-03-22 18:21:46.239371

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fa6a68f4fdfd"
down_revision: Union[str, Sequence[str], None] = "165a94c4e61f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "spam_filter",
        sa.Column("content_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("timestamp", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("content_hash"),
    )
    op.create_index(
        op.f("ix_spam_filter_timestamp"), "spam_filter", ["timestamp"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_spam_filter_timestamp"), table_name="spam_filter")
    op.drop_table("spam_filter")
    # ### end Alembic commands ###
